# Generated by Django 6.1 on 2026-09-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="登录账号"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="密码哈希"),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="姓名/昵称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="角色代码"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="角色名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="说明"),
                ),
                ("permissions", models.JSONField(default=list, verbose_name="权限点")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="内置角色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="令牌"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="签发时间"),
                ),
                (
                    "last_access_at",
                    models.DateTimeField(auto_now=True, verbose_name="最近访问"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="adminapi.adminuser",
                        verbose_name="管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录令牌",
                "verbose_name_plural": "登录令牌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="操作账号"
                    ),
                ),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                (
                    "target",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="对象"
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="详情"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="adminapi.adminuser",
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="adminuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="adminapi.role",
                verbose_name="角色",
            ),
        ),
    ]
