# Generated by Django 6.1 on 2026-09-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapi", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("sync", "同步"), ("async", "异步")],
                        default="sync",
                        max_length=16,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("processing", "处理中"),
                            ("success", "全部成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="题目总数")),
                ("succeeded", models.IntegerField(default=0, verbose_name="成功")),
                ("failed", models.IntegerField(default=0, verbose_name="失败")),
                (
                    "skipped",
                    models.IntegerField(default=0, verbose_name="跳过（重复）"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="导入数据")),
                ("results", models.JSONField(default=list, verbose_name="逐题结果")),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="失败原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to="adminapi.adminuser",
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "导入任务",
                "verbose_name_plural": "导入任务",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="标签名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("knowledge", "知识点"),
                            ("difficulty", "难度"),
                            ("qtype", "题目类型"),
                            ("scene", "使用场景"),
                        ],
                        max_length=32,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="说明"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["category", "name"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_bindings",
                        to="core.document",
                        verbose_name="题目文档",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="adminapi.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目标签",
                "verbose_name_plural": "题目标签",
                "unique_together": {("question", "tag")},
            },
        ),
    ]
