# Generated by Django 6.1 on 2026-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="集合名"
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="文档_id"
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="文档数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "unique_together": {("collection", "doc_id")},
            },
        ),
    ]
